server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://192.168.144.76:1450;databaseName=finflex;Encrypt=False;
    username: grup1
    password: inFina2030!!**
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  threads:
    virtual:
      enabled: true
  mail:
    password: ktwozsdcaejgmuzo
    host: smtp.gmail.com
    username: noreply4finflex@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kafka:
  bootstrap-servers: localhost:9092
  group-id: mail-group

front-end:
  url: http://localhost:3000
  password-rest-mail-template:
    name: forgot_template.ftl
    subject: "Password Reset"
  register-mail-template:
    name: register_template.ftl
    subject: "Verify Email"