server:
  port: 8081
#postgres
spring:
  datasource:
    url: jdbc:sqlserver://192.168.144.76:1450;databaseName=finflex;Encrypt=False;
    username: grup1
    password: inFina2030!!**
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  threads:
    virtual:
      enabled: true

jwt:
  secretkey: VuwNFfgWWsAfVaMllWxGsWA8hP9c4KU1yOJLqlpumbTmXIRjAfi17LGNtoqUnDR
  audience: finflexteamwois
  issuer: wois
api:
  url: ${RATES_URL}
logging:
  config: classpath:logback-spring.xml