server:
  port: 8080
#postgres
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:sqlserver://192.168.144.76:1450;databaseName=finflex;Encrypt=False;
    username: grup1
    password: inFina2030!!**
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  threads:
    virtual:
      enabled: true

jwt:
  secretkey: VuwNFfgWWsAfVaMllWxGsWA8hP9c4KU1yOJLqlpumbTmXIRjAfi17LGNtoqUnDR
  audience: finflexteamwois
  issuer: wois
kafka:
  bootstrap-servers: localhost:9092
  topics:
    user:
      register: send-register-mail
      forgot-password: send-forgot-mail